name: Latest blog post workflow
on:
  schedule:
    # Runs every hour at minute 25 to avoid peak traffic
    - cron: '25 * * * *'
  push:
    branches:
      - main
  workflow_dispatch: # Run workflow manually

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Pull in hussainweb.me posts
        uses: gautamkrishnar/blog-post-workflow@v1.8.6
        with:
          feed_list: "https://hussainweb.me/rss.xml"
          committer_username: "hussainweb"
          committer_email: "hussainweb@users.noreply.github.com"
          commit_message: "docs: update latest blog posts from hussainweb.me"

